mapping_dict = {0:'',
                1:'Bronze I',
                2:'Bronze II',
                3:'Bronze III',
                4:'Silver I',
                5:'Silver II',
                6:'Silver III',
                7:'Gold I',
                8:'Gold II',
                9:'Gold III',
                10:'Diamond I',
                11:'Diamond II',
                12:'Diamond III',
                13:'Mythic I',
                14:'Mythic II',
                15:'Mythic III',
                16:'Legend I',
                17:'Legend II',
                18:'Legend III',
                19:'Masters'
                }